packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.1.0
  '@types/node': ^22.10.10
  '@vitest/coverage-v8': ^3.0.4
  automd: ^0.3.12
  bumpp: ^10.0.1
  eslint: ^9.19.0
  jiti: ^2.4.2
  lint-staged: ^15.4.3
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vitest: ^3.0.4
  '@unocss/reset': ^65.4.3
  unocss: ^65.4.3
  vite: ^6.0.11
  vite-plugin-ejs: ^1.7.0
  '@types/fs-extra': ^11.0.4
  chokidar: ^3.6.0
  citty: ^0.1.6
  colorette: ^2.0.20
  consola: ^3.4.0
  fs-extra: ^11.3.0
  pathe: ^2.0.2
  perfect-debounce: ^1.0.0
  tinyglobby: ^0.2.10
  '@types/semver': ^7.5.8
  c12: ^2.0.1
  confbox: ^0.1.8
  defu: ^6.1.4
  hookable: ^5.5.3
  semver: ^7.6.3
  type-fest: ^4.33.0
  yaml: ^2.7.0
  es-toolkit: ^1.31.0
