packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@types/node': ^22.13.5
  '@vitest/coverage-v8': ^3.0.7
  automd: ^0.3.12
  bumpp: ^10.0.3
  eslint: ^9.21.0
  jiti: ^2.4.2
  lint-staged: ^15.4.3
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vitest: ^3.0.7
  '@unocss/reset': ^66.0.0
  unocss: ^66.0.0
  vite: ^6.2.0
  vite-plugin-ejs: ^1.7.0
  '@types/fs-extra': ^11.0.4
  chokidar: ^3.6.0
  citty: ^0.1.6
  colorette: ^2.0.20
  consola: ^3.4.0
  fs-extra: ^11.3.0
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  tinyglobby: ^0.2.12
  '@types/semver': ^7.5.8
  c12: ^2.0.4
  confbox: ^0.1.8
  defu: ^6.1.4
  hookable: ^5.5.3
  semver: ^7.7.1
  type-fest: ^4.35.0
  yaml: ^2.7.0
  es-toolkit: ^1.32.0
